# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.

# Setup
title:               Yara
tagline:             'My first blog'
description:         'Blog setup - A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Yara Sanchez Corrales
  url:               https://twitter.com/yara_elena
  email:             ysanchez@mrc-lmb.cam.ac.uk

# Custom vars
version:             1.0.0
